include:
  - Misc:
    - Contest:
      - Makefile:
        - misc/Makefile
    - 'How Did We Get Here?':
      - Fast I/O:
        - misc/speed/fast_io.java
    - Tools:
      - '<random>':
        - misc/random.java
    - Algorithms:
      - Manacher Algo:
        - misc/Manacher.java
      - TreeDiameter:
        - misc/TreeDiameter.java
      - GCD On Path (max, min etc):
        - misc/GCDOnPath.java
      - SLiding Window:
        - misc/SlidingWindow.java
      - Cycle IN Directed Graph:
        - misc/CycleinDGPrint.java
      - NegCycle IN Directed Graph:
        - misc/negCycleDetectDG.java
      - UpDown Algo IN Tree:
        - misc/UpDownDist.java
      - KMP:
        - misc/KMP.java
      - Palindrome Subsequence:
        - misc/palSubsequence.java
      - Longest Increasing Subsequence:
        - misc/lis.java
  - Data Structures:
    - Fenwick Tree:
      - ds/FT.java
    - Segment Tree (SIMPLE):
      - ds/SegTreeSimple.java
    - Lazy Segment Tree (SIMPLE):
      - ds/LazySimple.java
    - Binary Lifting (1 based):
      - ds/BinaryLiftting.java
    - DSU:
      - ds/DSU.java
    - SparseTable:
      - ds/SparseTable.java
    - EulerTour:
      - ds/euler_tour.java
    - Heavy-Light Decomposition:
      - ds/hld.hpp
  - Graph:
    - Modeling:
      - graph/model.tex
    - Matching/Flows:
      - Dinic's Algorithm:
        - graph/flows/dinic.hpp
      - Minimum Cost Flow:
        - graph/flows/min-cost-flow.hpp
      - Bipartite Minimum Cover:
        - graph/flows/min-bi-cover.hpp
      - Edmonds' Algorithm:
        - graph/flows/edmonds.hpp
      - Minimum Weight Matching:
        - graph/flows/min-weight-general.hpp
      - Stable Marriage:
        - graph/flows/marriage.hpp
      - Kuhn-Munkres algorithm:
        - graph/flows/km.hpp
    - Shortest Path Faster Algorithm:
      - graph/spfa.hpp
    - Strongly Connected Components:
      - graph/scc.hpp
      - 2-Satisfiability:
        - graph/2sat.hpp
    - Biconnected Components:
      - Articulation Points:
        - graph/tarjan-ap.hpp
      - Bridges:
        - graph/tarjan-b.hpp
    - Triconnected Components:
      - graph/tcc.hpp
    - Centroid Decomposition:
      - graph/centroid_decomposition.java
    - Minimum Mean Cycle:
      - graph/min-mean-cycle.hpp
    - Dominator Tree:
      - graph/dominator-tree.hpp
    - Manhattan Distance MST:
      - graph/manhattan-mst.hpp
  - Math:
    - Number Theory:
      - Miller-Rabin:
        - math/number-theory/miller-rabin.hpp
      - Linear Sieve:
        - math/number-theory/prime_sieve.java
      - Get Factors and SPF Fucn: 
        - math/number-theory/allfactor.java
      - Extended GCD:
        - math/number-theory/extgcd.hpp
      - Chinese Remainder Theorem:
        - math/number-theory/crt.hpp
      - Chinese Sieve:
        - math/number-theory/djs.hpp
    - Combinatorics:
      - Comb: 
        - math/combinatorics/Main.java
    - Algebra:
      - Formal Power Series:
        - math/algebra/formal-power-series.hpp
    - Theorems:
      - math/theorems.tex
  - Numeric:
    - Barrett Reduction:
      - numeric/barrett-reduction.hpp
    - Long Long Multiplication:
      - numeric/ll-mul.hpp
    - Fast Fourier Transform:
      - numeric/fft.hpp
      - numeric/fft-usage.hpp
    - Fast Walsh-Hadamard Transform:
      - numeric/fwht.hpp
    - Subset Convolution:
      - numeric/subset-convolution.hpp
    - Linear Recurrences:
      - Berlekamp-Massey Algorithm:
        - numeric/berlekamp-massey.hpp
      - Linear Recurrence Calculation:
        - numeric/linear-recurrence.hpp
    - Polynomial Interpolation:
      - numeric/interpolation.hpp
    - Simplex Algorithm:
      - numeric/simplex.hpp
  - Geometry:
    - Point:
      - geometry/point.hpp
      - Quarternion:
        - geometry/quaternion.hpp
      - Spherical Coordinates:
        - geometry/spherical.hpp
    - Segments:
      - geometry/segments.hpp
    - Angular Sort:
      - geometry/angular-sort.hpp
    - Convex Polygon Minkowski Sum:
      - geometry/minkowski-sum.hpp
    - Point In Polygon:
      - geometry/point-inclusion.hpp
      - Convex Version:
        - geometry/convex-inclusion.hpp
    - Closest Pair:
      - geometry/closest-pair.hpp
    - Minimum Enclosing Circle:
      - geometry/min-enclosing-circle.hpp
    - Half Plane Intersection:
      - geometry/half-plane-intersection.hpp
  - Strings:
    - Knuth-Morris-Pratt Algorithm:
      - strings/kmp.hpp
    - Suffix Array:
      - strings/suffix-array.hpp
    - Suffix Tree:
      - strings/suffix-tree.hpp
    - Cocke-Younger-Kasami Algorithm:
      - strings/cyk.hpp
    - Z Value:
      - strings/z-value.hpp
    - Minimum Rotation:
      - strings/min-rotation.hpp
    - Palindromic Tree:
      - strings/palindromic-tree.hpp
  - UTILITY:
    - misc/Utility.java

dependencies:
  show: true
  ignore_cycles: false
