include:
  - Misc:
    - Contest:
      - Fast I/O:
        - misc/speed/fast_io.java
    - Tools:
      - '<random>':
        - misc/random.java
    - Algorithms:
      - Manacher Algo:
        - misc/Manacher.java
      - TreeDiameter:
        - misc/TreeDiameter.java
      - GCD On Path (max, min etc):
        - misc/GCDOnPath.java
      - SLiding Window:
        - misc/SlidingWindow.java
      - NegCycle IN Directed Graph:
        - misc/negCycleDetectDG.java
      - UpDown Algo IN Tree:
        - misc/UpDownDist.java
      - KMP:
        - misc/KMP.java
      - Palindrome Subsequence:
        - misc/palSubsequence.java
      - Longest Increasing Subsequence:
        - misc/lis.java
  - Data Structures:
    - Fenwick Tree:
      - ds/FT.java
    - Segment Tree (SIMPLE):
      - ds/SegTreeSimple.java
    - Lazy Segment Tree (SIMPLE):
      - ds/LazySimple.java
    - Binary Lifting (1 based):
      - ds/BinaryLiftting.java
    - DSU:
      - ds/DSU.java
    - SparseTable:
      - ds/SparseTable.java
    - EulerTour:
      - ds/euler_tour.java
  - Math:
    - Number Theory:
      - Linear Sieve:
        - math/number-theory/prime_sieve.java
      - Get Factors and SPF Fucn: 
        - math/number-theory/allfactor.java
    - Combinatorics:
      - Comb: 
        - math/combinatorics/Main.java
  - UTILITY:
    - misc/Utility.java

dependencies:
  show: true
  ignore_cycles: false
